### ISSUE TITLE
Remove unused dependency `anyhow`

### ISSUE THREAD

**Issue by oriontvv** [TrueLayer/retry-policies#17]
## Motivations
Unused dependency `anyhow` should be removed - it slow down build and could expand bin size as transitive dependency

## Solution

We can add ci linter like [machete](https://github.com/bnjbvr/cargo-machete)

```
name: Cargo Machete
on:
  pull_request: { branches: "*" }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Machete
        uses: bnjbvr/cargo-machete@main
```

## Alternatives
* Add [cargo udeps](https://github.com/est31/cargo-udeps) (slower, more accurate)
* Don't add any linter

## Additional context

We could add dependabot as well to keep deps fresh and clean
